### ISSUE TITLE
laravel 4.2.*

### ISSUE THREAD

**Issue by ganapathi-threesquare** [Zizaco/confide-mongo#9]
Problem 1
    - Installation request for zizaco/confide-mongo dev-master -> satisfiable by zizaco/confide-mongo[dev-master].
    - zizaco/confide-mongo dev-master requires zizaco/mongolid-laravel \* -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by ravanscafi** [comment]
This was long fixed, sorry for the delay.
